// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetPageDetail(arg1, arg2) {
  return window['go']['main']['App']['GetPageDetail'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function CloseFile(arg1) {
  return window['go']['main']['App']['CloseFile'](arg1);
}
